sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "hmvvO2qOj7TfoRQBBbRvmd1p6SHEds7hhb74o4IBtL8wL35xPrz1b81bT3y1nz472G57K72x/zXlcJeCAPFlwCPQBwIGJkLejrM9RV96gzGYLHYebTiHhMcR1GKxOJxFw2sDKl6UHA+JekSUHhtUNYIYDl/ZBc1c/rfl/V/z6ICP/G/O5Kt2CAyBdasMIwg+VHVZqo2wB2nZdFo2Z8hY6+nE8fWLhNBZHVba1H6CgsD/jdxyEEXmaaMt0fI0xFsPhfV+XZemsPncBZAelbFdroLtCDK1VxknnKX0RHmA3z4KlNuCkBenAUp2LVmsy45YDmDtgmc9/9lCziMUbz6bM+7pLd9fsZ5pFhkmIuvFVZYOneyDgOAWVORSkc0BvfGYuCqwMlYkvJ+46T/QExvadESJCuqJnzmEoqkYTvKgvth43FDhqfT4LtflbPUIx10CJokkQfPXUwD0C/1NmCqjCIr3gcoZFmDx/EmJ0tIY0XVBL2BWwe/0Qv9K+OZZTNUEghpRjKwHA2lxG9BJaGaSnGfc2fape8E5UBWb8T+KzjXzkIgr9ptDk93YvzkzP2oI+W52KgeJ/sPmT/0nR6hsHAngwQoNklVQbnd7s3x7kR7TEPr0tBFc9P1/itcSZ+oaCnwihLvlFTwgfuLfEJu4m20uyTje9TRiZOshqs5LovQ="
  - secure: "XIwSIXRaIdQEzAw9AxhStQlr5P/zxFREVhLzP8VrphjnmKAcKo9280wP2UJv7HaqOjLDOI3ZUHQZDrv8NnVcxFOOTRPZDtI4sKLLyriXIosD9jkqcc9blPHtQaKfJ3rO6rdRx1Ob4c/VF+hvOBqhE0i0wbV7mrp6d3cSUHSMNdIN515OMY7vSIFJ8znPDA829F6jxeT/ZbriOmIea5z+LCjb14TpK6vmXUS3WAu46kPKITPJVfWOX6s9JSbrp3kmJ8Zvf9UAXMbNgx1Gn6+jcGYvNoge/Nph6wQQnOcBKatdL4NNStVUNw+hg2PNNvbxxKlkKS0PMg8akXfK7QEOV6E7Uo4VtHJdzbpkrP3kEEMXOoYfds2o8AMxp6/qE8kqsMdELLZpoTmhGY3c6XJcNHtihpMne+aaHPM/fQ37qPz1HztACuzIh61f10+AvHAjY2Mrun6dWD2e+Pk8UQbRloDUoSCe+JBpl0yj9uXIZ0uX+oAeV25mhV8SHpDr5COKxNau5x/yvWS/lSSAalnbPpbck4OtFta9cwGzymQXS2MeT7RypXo+gfDmhYVjQ9s/uwwuHBOzM48AJ0urp/tzCilWmj+4njm5Gy6o/srJHwwsB9uCSbfgdVOXCf24m41oaNz03jHX9WZVTtBWPOmJF/cmRyautmhCqmTpGGfLu9w="
  - secure: "ErNlzx+/tQict8+25xKO+JXSILtwyAhtewgd1raJ5H8pwBs9wp3RKj3sWDfXQK9xGTkpWE25nUn0TngSGw7bD59JbKty6O7Opi6rRTxkw/K+zape4op/5LlMuE8Nzt+0JkCWuj1t2Q2Zj+ajfSvotNAly7G9h86LdarZDXakKSt0+uHx/pirO/CtzBpyhruXGet9NsfVF7qsIn2jLUKKz6QTQRQyZwdFnuTqdL4aYqGNsBESwW4fb9v5AgMnSJ5ljDnH4Hwhz2plQgcPDFkRMKJEhozxnrliIKk4aXuosHNadSv9jFz0jk9PCqApA8Kfao+QfP/CZFsg7A4bKbqmsC6y0amRkwipgyiw4+n+M3R7AX9gw52zOSku2oGLz1PFm/5x1H5C63j2H7uiP0GOoK3RyTmVBsR0uBvhARMKg/SXpBo5ULVFn/ijDl1DrIHrkJyS7T/QoMV8KSNFjXao5wU2MlMcwiTQRnXcMi4la2R3ZoP5xhwYSZHp0cg3m+snRj86fYhdJvuz4nu1qszVJZmHOhpT94eF2ICL1QrOImX1ux9UP82VHe0CYUZdrQ58BgqrxLdhsXu9Yam5mFfOAYeT3KsV30/1S10XwkolLKQ3KFlcO1+DhwMaJ16L+GPvatWO38aVGfAxbSMZWVjL2p9Aj147W2K7jD20QVVSYr4="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
