sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "VXreJtozdVuTrLe+i5RL/edqxN+VRiiAe0zJe8UX6mLA4K7lDgp1/FPfMm6m1JWZBeE8kKKCMKRJYtG1gPU1BXcDM1KUYwZgOAIm8+oLm1hj+/FXW/6JdaoSqwM3eCrvbSdoJLTd7aDJNNqiDK382VH468A6dVb/AVXQtMPrUzUN1bscErMYGT6hhCXzO5UYOPlf+tN5fwx5AozESrb5XYv917c0MkU5Z/qmMTcZ0ziROAdkJa7eh1lJQTxK00oZEqzDg8/XfSinfHDEoWm1oIAMRcOBJKcSYq2cIwE/9TOyAa8VsloWzmrG4P/Sphmwz34DvFaPubljDMIaeA+PVxMZ06y4isj4KoRFRtqlaJ785M14mnNhbupA7z/x0KFCbXoOA0wPY/DJ1EqzFgjBW2+ilcLv+MEHJDrugYHDtvQXI2FJ/Cy1ARkZrKDPGTibUO3HBfrvZ/vQI5aGa8yy05/D9yRNbxHt3XwK5tbFnRjdPAEzveBEQjnwjqPuIZ8S1HMrH8YbjNOlIe97PGPe5mm2AbD7WE1B1kZOVh0LzdOaEao+xY3kcDXO9LzFoLxFaGRZsOnJYMRHp7hqZZlHKeM07IFwiBtLPN0v+BVFPaEjVTw0BQ8yae/RFR5KmNwq1j8fmriylESE0FkNMsD4AheQK6k5+ir7FMvO9fxLzLs="
  - secure: "XIwSIXRaIdQEzAw9AxhStQlr5P/zxFREVhLzP8VrphjnmKAcKo9280wP2UJv7HaqOjLDOI3ZUHQZDrv8NnVcxFOOTRPZDtI4sKLLyriXIosD9jkqcc9blPHtQaKfJ3rO6rdRx1Ob4c/VF+hvOBqhE0i0wbV7mrp6d3cSUHSMNdIN515OMY7vSIFJ8znPDA829F6jxeT/ZbriOmIea5z+LCjb14TpK6vmXUS3WAu46kPKITPJVfWOX6s9JSbrp3kmJ8Zvf9UAXMbNgx1Gn6+jcGYvNoge/Nph6wQQnOcBKatdL4NNStVUNw+hg2PNNvbxxKlkKS0PMg8akXfK7QEOV6E7Uo4VtHJdzbpkrP3kEEMXOoYfds2o8AMxp6/qE8kqsMdELLZpoTmhGY3c6XJcNHtihpMne+aaHPM/fQ37qPz1HztACuzIh61f10+AvHAjY2Mrun6dWD2e+Pk8UQbRloDUoSCe+JBpl0yj9uXIZ0uX+oAeV25mhV8SHpDr5COKxNau5x/yvWS/lSSAalnbPpbck4OtFta9cwGzymQXS2MeT7RypXo+gfDmhYVjQ9s/uwwuHBOzM48AJ0urp/tzCilWmj+4njm5Gy6o/srJHwwsB9uCSbfgdVOXCf24m41oaNz03jHX9WZVTtBWPOmJF/cmRyautmhCqmTpGGfLu9w="
  - secure: "ErNlzx+/tQict8+25xKO+JXSILtwyAhtewgd1raJ5H8pwBs9wp3RKj3sWDfXQK9xGTkpWE25nUn0TngSGw7bD59JbKty6O7Opi6rRTxkw/K+zape4op/5LlMuE8Nzt+0JkCWuj1t2Q2Zj+ajfSvotNAly7G9h86LdarZDXakKSt0+uHx/pirO/CtzBpyhruXGet9NsfVF7qsIn2jLUKKz6QTQRQyZwdFnuTqdL4aYqGNsBESwW4fb9v5AgMnSJ5ljDnH4Hwhz2plQgcPDFkRMKJEhozxnrliIKk4aXuosHNadSv9jFz0jk9PCqApA8Kfao+QfP/CZFsg7A4bKbqmsC6y0amRkwipgyiw4+n+M3R7AX9gw52zOSku2oGLz1PFm/5x1H5C63j2H7uiP0GOoK3RyTmVBsR0uBvhARMKg/SXpBo5ULVFn/ijDl1DrIHrkJyS7T/QoMV8KSNFjXao5wU2MlMcwiTQRnXcMi4la2R3ZoP5xhwYSZHp0cg3m+snRj86fYhdJvuz4nu1qszVJZmHOhpT94eF2ICL1QrOImX1ux9UP82VHe0CYUZdrQ58BgqrxLdhsXu9Yam5mFfOAYeT3KsV30/1S10XwkolLKQ3KFlcO1+DhwMaJ16L+GPvatWO38aVGfAxbSMZWVjL2p9Aj147W2K7jD20QVVSYr4="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
